variable "projectPrefix" {}
variable "name" {}
variable "environment" {}
variable "aws_region" {}
variable "aws_az" {}
variable "vpc_id" {}
variable "subnet_id" {}
variable "key_name" {}
variable "linux_instance_type" {}
variable "linux_associate_public_ip_address" {}
variable "linux_root_volume_size" {}
variable "linux_data_volume_size" {}
variable "linux_root_volume_type" {}
variable "linux_data_volume_type" {}
variable "owner" {}
variable "adminPassword" {}
variable "adminUserName" {}
variable "tags" {}
variable "security_source" {}
