# volterra Environment
variable "projectPrefix" {}
variable "name" {}
variable "environment" {}
variable "sshPublicKey" {}
variable "sshPublicKeyPath" {}
variable "aws_access_key" {}
variable "aws_secret_key" {}
variable "aws_region" {}
variable "aws_az" {}
#variable "aws_vpc_id" {}
variable "vpc_cidr" {}
#variable "aws_public_subnet_id" {}
#variable "aws_private_subnet_id" {}
variable "public_subnet_cidr" {}
variable "private_subnet_cidr" {}
variable "api_p12_file" {}
variable "tenant_name" {}
variable "namespace" {}
variable "delegated_dns_domain" {}
variable "api_url" {}
variable "tags" {}
variable "fleet_label" {}
variable "instance_type" {}
variable "xcs_tf_action" {}
